### ISSUE TITLE
예약 알림 한 사람당 1개만 생성 가능 

### ISSUE THREAD

**Issue by mybloom** [depromeet/KnockKnock-Backend#249]
### Describe

기획상 예약 알림 한 사람당 1개만 생성 가능하도록 수정

### Work

- [x] 예약 알림 한 사람당 1개만 생성하도록 유효성 확인
- [x]  알림 발송 시, 알림 발송 권한 확인

### Additional

- Group.validUserIsMemberOfGroup()  이 메세드 사용하면 되나 Group엔티티 사용시 불필요하게 연관관계 엔티티가 조회되는 현상이 있어서 사용하지 않는 것으로 개발 
- @ImNM 님 해당 부분 사용 시 발생쿼리 한 번 확인해보세요

**Comment by ImNM** [comment]
요거 그룹을 그냥 개발편하게
그룹유저도 그룹 도메인안에 넣은거에유!

**Comment by mybloom** [comment]
user 그룹사용자 모두  in절 , notification, category등
불필요한 쿼리 많이 발생되고 있어요.
한번 확인해 보는 걸 추천드립니다
