### ISSUE TITLE
즉시 알림 발송

### ISSUE THREAD

**Issue by mybloom** [depromeet/KnockKnock-Backend#80]
### Describe

즉시 알림 발송

### Work

- [ ] POST : createTopic
- [ ] POST : sendMessageToTopic
- [ ] POST : subscribeToTopic 
- [ ] POST : unsubscribeToTopic 

### Additional

친구방, 홀로외침 방 모두 토픽 구독으로 처리하려고 합니다. 
그렇게 처리한 이유는, 알림 설정 on/off 시 실시간으로 똑똑DB를 조회하지 않고   이미 FCM에 저장되어 있는 token목록에 알림을 전달하도록 하기 위해서 입니다. 
사용자의 on/off 설정 시에는 토픽 구독 설정/해지 로직을 사용합니다.

**Comment by ImNM** [comment]
움... 저는 토픽구독울 알림구현할때
사용하지 않았었던것같아요

티키타카 진행하면서 차단 로직을 수행할때
같은 방에 차단한 유저가 있다면 빼고 보내줘야하는
경우도있었고요!!

저희 앱같은경우
야간알림만을 끈경우에는
토픽구독으로 수행했을때
안보내고 싶어도 보내지는 경우가 있더라고요
차단로직 같은게 필요할수도있고!!

@mybloom 
어떻게 생각하시나용??

**Comment by mybloom** [comment]
찬진님! 안그래도 다른 분들은 어떻게 생각하실까 궁금해서 먼저 코멘트 남겨두었었는데요. 빠르게 답변해주셔서 감사합니다!
야간 알람은 토픽 백업/복원으로 고민하고 있었는데요. 

한번 더 고민해보겠습니다.

**Comment by mybloom** [comment]
- 처음 계획한 FCM 구독으로 처리하지 않고, 서비스 DB에서 셋팅한 알림 정보를 실시간 조회해 FCM 알림 전송으로 구현
