### ISSUE TITLE
그룹 초대,가입 요청 승인

### ISSUE THREAD

**Issue by ImNM** [depromeet/KnockKnock-Backend#89]

**Comment by mybloom** [comment]
그룹 관련이라 여기에 남깁니다.
tbl_group_user테이블에 group_id,user_id 합쳐서 unique 권한 추가하는 게 좋을 것 같아요

**Comment by ImNM** [comment]
> 그룹 관련이라 여기에 남깁니다. tbl_group_user테이블에 group_id,user_id 합쳐서 unique 권한 추가하는 게 좋을 것 같아요

검증은 항상 거치긴하는데 혹시모르니!
좋습니다 이이슈에 추가해서 올릴게영!
